packages:
  - packages/*

catalogs:
  astro:
    '@astrojs/cloudflare': 12.5.0
    '@astrojs/mdx': 4.2.4
    '@astrojs/react': 4.2.4
    '@astrojs/rss': 4.0.11
    '@astrojs/sitemap': 3.3.0
    '@astrojs/tailwind': 6.0.2
    '@astrojs/ts-plugin': 1.10.4
    astro: 5.9.0
    astro-auto-import: 0.4.4
    astro-cloudinary: 1.3.2
    astro-embed: 0.9.0
    astro-seo: 0.8.4
  eslint:
    '@virtual-live-lab/eslint-config': 2.3.0
    eslint: 9.36.0
    typescript-eslint: 8.44.0
  expressive-code:
    astro-expressive-code: 0.41.1
    '@expressive-code/plugin-collapsible-sections': 0.41.1
  markdown:
    '@types/mdast': 4.0.4
    katex: 0.16.22
    marked: 15.0.8
    mdast-util-to-string: 4.0.0
    rehype-katex: 7.0.1
    rehype-unwrap-images: 1.0.0
    remark: 15.0.1
    remark-emoji: 5.0.1
    remark-math: 6.0.0
    unified: 11.0.5
  prettier:
    '@virtual-live-lab/prettier-config': 2.0.19
    prettier: 3.5.3
    prettier-plugin-astro: 0.14.1
  react:
    '@types/react': 19.1.2
    '@types/react-dom': 19.1.2
    react: 19.1.0
    react-dom: 19.1.0
  stylelint:
    '@double-great/stylelint-a11y': 3.0.3
    '@virtual-live-lab/stylelint-config': 3.0.4
    stylelint: 16.18.0
    stylelint-config-html: 1.1.0
    stylelint-config-recess-order: 6.0.0
    stylelint-config-recommended: 16.0.0
    stylelint-config-sass-guidelines: 12.1.0
    stylelint-config-standard: 38.0.0
    stylelint-config-standard-scss: 14.0.0
    stylelint-declaration-block-no-ignored-properties: 2.8.0
    stylelint-value-no-unknown-custom-properties: 6.0.1
  textlint:
    '@textlint/textlint-plugin-markdown': 14.6.0
    textlint: 14.6.0
    textlint-rule-preset-japanese: 10.0.4
  tsconfig:
    '@virtual-live-lab/tsconfig': 2.1.20
  typescript:
    typescript: 5.8.3
  vitest:
    vitest: 3.1.1
    '@vitest/coverage-v8': 3.1.1

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - workerd
